### PR TITLE
Added pipeline-github to tools.cdt

### PR DESCRIPTION
**Pull request by jonahgraham**
Similar to #204 but for tools.cdt

### CODE REVIEW

**Comment by jonahgraham** [comment]
xref: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1696

**Comment by fredg02** [comment]
Thanks for the PR. I will install the plugin, once no builds are running.

**Comment by fredg02** [comment]
Plugin has been installed.

**Comment by jonahgraham** [comment]
Thanks Fred.

**Pull request merged**
