### PR TITLE
OMR: Add mac11-aarch64-8

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@fredg02 for review. I think it should work but I am unable to test without admin node privlages.

**Comment by fredg02** [comment]
Commit has been merged and deployed.

Connection log shows:
`bash: wget: command not found`

**Comment by fredg02** [comment]
@AdamBrousseau ping

**Comment by AdamBrousseau** [comment]
Fixed

**Pull request merged**
