### PR TITLE
OMR: Modify java options for shared jenkins node connections

### PR DESCRIPTION
**Pull request by jdekonin**
* disable dump creation, reduce Xmx
* eclipse-openj9/openj9#16173

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
@pshipton @AdamBrousseau for review

**Review by AdamBrousseau — APPROVED** [review]
lftm assuming we get agreement on the list of options we want.

**Comment by jdekonin** [comment]
Updated with those options as requested.

**Comment by jdekonin** [comment]
@fredg02, this is ready to merge and deploy.  Thanks

**Comment by fredg02** [comment]
Merged and deployed.

**Comment by AdamBrousseau** [comment]
@fredg02 the machine [mac11-aarch64-08](https://ci.eclipse.org/omr/computer/mac11-aarch64-08) is offline penging script approval. I tried pasting in the ssh command from this pr and it says it needs approval. Not sure what is up. Could you take a look please?

**Comment by fredg02** [comment]
Done.

**Pull request merged**
