### PR TITLE
Add Build Blocker plugin to sirius

### PR DESCRIPTION
**Pull request by heurtematte**
Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4301

### CODE REVIEW

**Comment by lredor** [comment]
@heurtematte Please, can you merge this PR to solve the issue [4301](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4301) ?

**Comment by heurtematte** [comment]
> @heurtematte Please, can you merge this PR to solve the issue [4301](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4301) ?

@lredor it is already live.

**Review by fredg02 — APPROVED** [review]

**Comment by lredor** [comment]
@heurtematte @fredg02 Thanks for adding this plug-in. For information, unfortunately, it is not "compatible" with the "Pipeline Multibranch" jobs (as explained in https://github.com/eclipse-sirius/sirius-desktop/pull/269).

**Comment by heurtematte** [comment]
@lredor should we remove the plugin?

**Comment by lredor** [comment]
There is no preference for us. But to avoid "noise" or future maintenance for a plugin that isn't used, maybe it's simpler for you.

**Comment by fredg02** [comment]
@heurtematte please remove the plugin

**Pull request merged**
