### PR TITLE
OpenJ9: Machine additions and updates

### PR DESCRIPTION
**Pull request by jdekonin**
* rename existing cent7p8j91 -> cent7-ppcle-1 to match naming conventions

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
fyi @pshipton

**Comment by fredg02** [comment]
Please always comment when such a change is ready to be merged.

**Comment by jdekonin** [comment]
@pshipton, compiles are currently routed to ubuntu16 machines and there is no test label on these atm so there is no risk until the OpenJ9 pipeline changes are merged.

This change is ready to be merged.

**Comment by jdekonin** [comment]
This change is ready to be merged.

**Comment by fredg02** [comment]
Merged and deployed

**Pull request merged**
