### PR TITLE
OpenJ9: Retire non-existent nodes aix71-p8-1 -> aix71-p8-10

### PR DESCRIPTION
**Pull request by jdekonin**
* Rename aix71-p8-11 -> aix71-p8-20 to aix71-p8-1 -> aix71-p8-10 
* eclipse/openj9#8979

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
fyi @rajdeepsingh1 @pshipton

**Comment by jdekonin** [comment]
Unless @rajdeepsingh1 or @pshipton have objections, I believe this is ready to merge.

**Comment by pshipton** [comment]
No objections.

**Comment by rajdeepsingh1** [comment]
@jdekonin

Once the PR is merged the host names on the CECC machines will have to be set from 11-20 to 1-10 and the /etc/hosts modified for this change, since the configure parameter in Jenkins is going to be changed as well:

Ex: 


**FROM:** 
  command: "ssh -C -i /run/secrets/jenkins/ssh/id_rsa.openj9 jenkins@140.211.168.230 \"ssh -i ~/.ssh/id_rsa.aix jenkins@aix71-p8-11 'wget -qO slave.jar https://ci.eclipse.org/openj9/jnlpJars/slave.jar ; exec java -Xshareclasses:none -Xdump:none -jar slave.jar'\""


**TO:**

          command: "ssh -C -i /run/secrets/jenkins/ssh/id_rsa.openj9 jenkins@140.211.168.230 \"ssh -i ~/.ssh/id_rsa.aix jenkins@aix71-p8-1 'wget -qO slave.jar https://ci.eclipse.org/openj9/jnlpJars/slave.jar ; exec java -Xshareclasses:none -Xdump:none -jar slave.jar'\""



Other than that, no issues with the PR, ready to merge. The change mentioned above makes sense to be done after the PR is merged anyway.

**Comment by jdekonin** [comment]
I already updated /etc/hosts since 1-10 aren't in use anyways and the second commit in this PR makes updates to the node names and connections.

**Comment by fredg02** [comment]
Merged and deployed.

**Pull request merged**
