### PR TITLE
[OMR] Add CROSS_SYSROOT_RISCV64 env var to deb10 machine

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Related eclipse/omr#5755

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@fredg02 this is ready. I've made the change manually for now. Thanks.

**Comment by fredg02** [comment]
Change has been merged and deployed.

**Comment by AdamBrousseau** [comment]
Hey @fredg02 , we noticed today the variable has been removed from the machine again. I have added it back manually for the time being. Any idea why it's getting removed?

From config history, was removed via
```
2021-02-02_12-03-16 | Changed | SYSTEM
```

**Comment by fredg02** [comment]
Not sure why the variable got removed. I've redeployed the instance for good measure. Let me know if it happens again.

**Comment by AdamBrousseau** [comment]
Thanks, Fred, we'll keep an eye on it.

**Pull request merged**
