### PR TITLE
Add config for Artifactory server

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Depends #32
    
Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Depending on 32 because it will be a merge conflict.

Not sure if this will work. The [demo page](https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/artifactory) talks about a current known issue ([jfrog/HAP-1018](https://www.jfrog.com/jira/browse/HAP-1018))

**Comment by AdamBrousseau** [comment]
If this doesn't work, we would be forced back to archiving to Jenkins master which would greatly increase our disk usage and/or reduce our history.

**Comment by fredg02** [comment]
I've tried to set the Artifactory settings manually, but when testing the connection, it spits out: 
"Bad props auth token". :(

**Comment by AdamBrousseau** [comment]
Ok, sounds more like a bad token than a CasC problem. Let me confirm it or regen it and email it to you.

**Comment by fredg02** [comment]
Artifactory server settings were applied manually. Therefore I'm closing this PR for now.

**Pull request closed without merging**
