### PR TITLE
Adding new win2012 machine

### PR DESCRIPTION
**Pull request by rajdeepsingh1**
Signed-off-by: Rajdeep Singh <rajdeep.singh@ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
Looks good.  @fredg02 this is ready to merge & deploy.  Thanks.

**Comment by fredg02** [comment]
Change has been merged and deployed.

**Comment by jdekonin** [comment]
@fredg02, I don't see the machine in the jenkins node list.

**Comment by fredg02** [comment]
Sorry, I did not spot the difference between win2012-x86-6 and win2012**r2**-x86-6 in a list of 73 agents at first glance. The agent is there and online now.

Due to outdated plugins, the Jenkins instance had to be restarted.

**Comment by jdekonin** [comment]
Thank you @fredg02

**Pull request merged**
