### PR TITLE
Winstone path on pre-stop

### PR DESCRIPTION
**Pull request by heurtematte**
Winstone jar is now located in "executable" sub directory

### CODE REVIEW

**Comment by fredg02** [comment]
* Can you point to references about the changed Winstone path (code change, changelog, documentation)?
* Has this been tested successfully?

**Comment by heurtematte** [comment]
Identify throw k8s describe cmd complaining about winstone and jenkins instance failling with some OOM.

Tested! and only identify in docker image directly. I haven't find any related documentation.

**Comment by fredg02** [comment]
> Identify throw k8s describe cmd complaining about winstone and jenkins instance failling with some OOM.

Sorry, I don't get what you mean here.

**Comment by heurtematte** [comment]
see the result of this describe cmd. 

```
kubectl describe -n eclipselink pods eclipselink-0
```

image

**Comment by fredg02** [comment]
But the wrong path to Winstone is not the cause for the OOM...

**Comment by heurtematte** [comment]
No it's not related. I just said that I discovered this issue while debugging an OOM. 
And fixing the path allow to send a shutdown signal to jetty before stopping the pod.

**Comment by heurtematte** [comment]
Please accept this, I can't get real reason for last termination.

image

**Review by fredg02 — APPROVED** [review]

**Pull request merged**
