### PR TITLE
OpenJ9: Add 10 replacement AIX 7.1 machines

### PR DESCRIPTION
**Pull request by jdekonin**
* eclipse/openj9#8979

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
fyi @pshipton.  I also have build and test labels omitted so this should have no impact to jobs.

This change is ready to merge.

**Comment by fredg02** [comment]
Change has been merged and deployed.

The agents can't connect to the servers though:
`ssh: Could not resolve hostname aix71-p8-12: Name or service not known`

**Comment by jdekonin** [comment]
Thanks for merging.  The machines are connected now but it seems there is a problem with the environment variables not coming through.  Would you believe that we have to have the $ escaped?
Only the one env var defined is showing up as set.  I did aix71-p8-11 manually.
https://ci.eclipse.org/openj9/computer/aix71-p8-12/configure

```
          - key: "PATH"
            value: "/opt/freeware/bin:\$PATH"
```

**Comment by fredg02** [comment]
This is a YAML syntax error. Instead of:
```
      - envVars:
          env:
          - key: "LDR_CNTRL"
            value: "MAXDATA=0x80000000"
          env:
          - key: "AIXTHREAD_HRT"
            value: "true"
          env:
          - key: "PKG_CONFIG_PATH"
            value: "/opt/freeware/lib64/pkgconfig:/opt/freeware/lib/pkgconfig"
          env:
          - key: "PATH"
            value: "/opt/freeware/bin:$PATH"
```
It should be:
```
      - envVars:
          env:
          - key: "LDR_CNTRL"
            value: "MAXDATA=0x80000000"
          - key: "AIXTHREAD_HRT"
            value: "true"
          - key: "PKG_CONFIG_PATH"
            value: "/opt/freeware/lib64/pkgconfig:/opt/freeware/lib/pkgconfig"
          - key: "PATH"
            value: "/opt/freeware/bin:$PATH"
```

**Comment by fredg02** [comment]
I will fix this.

**Comment by fredg02** [comment]
Fixed.

**Comment by jdekonin** [comment]
Thanks @fredg02.  Yes I can see the syntax error now that its pointed out.  I'll fix up on my next change, assuming what you changed will work for either format?

**Comment by fredg02** [comment]
I've already fixed it in https://github.com/eclipse-cbi/jiro/commit/b2e939e3dcf15a203c905cd578bea96d04644d18. So there is no need for a "fix up".

**Comment by jdekonin** [comment]
ah, gotcha.  I was looking at pull request history and not the actual commits.  Thanks again.

**Pull request merged**
