### PR TITLE
Add pipeline-github-plugin to platform CI

### PR DESCRIPTION
**Pull request by jonahgraham**
This will allow Eclipse Platform to add comments from Jenkinsfile to PRs.

See https://github.com/eclipse-platform/eclipse.platform.resources/pull/11#issuecomment-1080978054

### CODE REVIEW

**Comment by jonahgraham** [comment]
@mbarbero - I hope this is an OK way of making this request? I am not even sure I edited the right part, so it is my best guess.

**Comment by mbarbero** [comment]
This is definitely a right way to make the request. The file to edit would be https://github.com/eclipse-cbi/jiro/blob/master/instances/eclipse.platform/config.jsonnet#L9 though. The one you edited is the generated one.

**Comment by jonahgraham** [comment]
Try 2 - I assume (hope) that is is you that regenerates the output files.

For now I am adding to just the platform one - if successful I suspect we will want to add it to jdt/equinox/platform.releng too and I will provide PRs at that time.

**Comment by mbarbero** [comment]
I'll deploy the change as soon as I see a good time where platform's jipp is slacking off...

**Comment by mbarbero** [comment]
Change has been deployed.

One little thing for the upcoming PR for jdt/equinox/...: the plugin id is `pipeline-github` rather than `pipeline-github-plugin` (see https://github.com/eclipse-cbi/jiro/blob/master/instances/eclipse.platform/config.jsonnet#L10)

**Comment by mbarbero** [comment]
btw, thanks for doing those new plugin requests via PR, it helps.

**Comment by jonahgraham** [comment]
Thanks @mbarbero - the change is working https://github.com/eclipse-platform/eclipse.platform.resources/pull/11#issuecomment-1084756752

And thanks for patiently teaching me how to make these PRs the correct way.

**Pull request merged**
