### PR TITLE
Add pipeline-github plugin for Eclipse Capella Jenkins

### PR DESCRIPTION
**Pull request by pdulth**
Change-Id: Ia18da91bf889ba8e8f726351782bc666bff83e52
Signed-off-by: Philippe DUL <philippe.dul@thalesgroup.com>

### CODE REVIEW

**Comment by pdulth** [comment]
Notice that in [codewind-jiro plugin list](https://github.com/eclipse-cbi/jiro/commit/8c482dd5f1003396e18aae5806e84c1c3557f2b4) the plugin github-branch-source is listed, but in capella, it is not listed but it seems already available in our CI.

**Comment by fredg02** [comment]
> Notice that in [codewind-jiro plugin list](https://github.com/eclipse-cbi/jiro/commit/8c482dd5f1003396e18aae5806e84c1c3557f2b4) the plugin github-branch-source is listed, but in capella, it is not listed but it seems already available in our CI.

The **github-branch-source** plugin has been added to the list of base-plugins (plugins that are installed by default), see https://github.com/eclipse-cbi/jiro/blob/master/jenkins-master-base/2.190.1/base-plugins

**Comment by pdulth** [comment]
> > Notice that in [codewind-jiro plugin list](https://github.com/eclipse-cbi/jiro/commit/8c482dd5f1003396e18aae5806e84c1c3557f2b4) the plugin github-branch-source is listed, but in capella, it is not listed but it seems already available in our CI.
> 
> The **github-branch-source** plugin has been added to the list of base-plugins (plugins that are installed by default), see https://github.com/eclipse-cbi/jiro/blob/master/jenkins-master-base/2.190.1/base-plugins

Oh ok, I will look a bit on how this jiro project works.
Thanks for the link and the merge

**Comment by fredg02** [comment]
Please note: the change has not been deployed yet.

**Comment by fredg02** [comment]
Change has been deployed. The plugin is now installed on the Capella JIPP.

**Comment by pdulth** [comment]
Thank you !

**Pull request merged**
