### PR TITLE
Add compile label to all omr nodes

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@fjeremic please review

**Review by fjeremic — APPROVED** [review]
We'll need to coordinate with eclipse/omr#6018 as there are changes suggested there.

**Review by fjeremic — APPROVED** [review]

**Comment by fjeremic** [comment]
This should be ok to merge anytime now.

**Comment by AdamBrousseau** [comment]
@fredg02 or @mbarbero can you action please? We have a coordinate merge on our end.

**Comment by fredg02** [comment]
Change has been merged and deployed.

**Comment by AdamBrousseau** [comment]
Thanks, Fred.

**Pull request merged**
