### PR TITLE
Remove z14 390 machines from use, rename z15 machines 5-8 to 1-4

### PR DESCRIPTION
**Pull request by jdekonin**
Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
fyi @pshipton

**Comment by jdekonin** [comment]
Can this please be merged and deployed?

**Comment by fredg02** [comment]
Change has been merged and deployed.

**Comment by jdekonin** [comment]
ty

**Pull request merged**
