### PR TITLE
OpenJ9: Removing Older Winx86 Machines

### PR DESCRIPTION
**Pull request by rajdeepsingh1**
Signed-off-by: Rajdeep Singh <rajdeep.singh@ibm.com>

### CODE REVIEW

**Comment by rajdeepsingh1** [comment]
- Removing all older (6) Windows x86 machines 
- Testing complete therefore adding remoteFS: F to `win2012-x86-6` (new machine)

**Comment by rajdeepsingh1** [comment]
@jdekonin FYI

**Review by jdekonin — APPROVED** [review]
Looks good.  @fredg02 this is good to merge and deploy.  Thank you in advance.

**Comment by fredg02** [comment]
This change has been merged and deployed.

**Pull request merged**
