### PR TITLE
Add plugins to GEF Jenkins

### PR DESCRIPTION
**Pull request by Hejado**
Signed-off-by: Nico Prediger <mail@nicoprediger.de>

### CODE REVIEW

**Comment by fredg02** [comment]
`github-branch-source` can be removed since it's already installed by default (see https://github.com/eclipse-cbi/jiro/blob/master/jenkins-master-base/2.190.1/base-plugins)

**Comment by Hejado** [comment]
You're right. I removed it.

I didn't know about the base-plugins file and looked at the plugins-list file from Xtext for reference.

**Comment by fredg02** [comment]
The plugins have been installed.

**Comment by Hejado** [comment]
Great! Thanks!

**Pull request merged**
