### PR TITLE
OpenJ9: Add parameter-separator plugin

### PR DESCRIPTION
**Pull request by AdamBrousseau**
New requirement via AdoptOpenJDK/openjdk-tests#2375

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Can we get this plugin added @mbarbero or @fredg02 ?
Thanks

**Comment by fredg02** [comment]
Adding this plugin will require a restart of the OpenJ9 Jenkins instance. Let us know, when there is a good time slot for that.

P.S.: This plugin should have a big disclaimer: "If you need this plugin, you are using too many parameters!!!" :stuck_out_tongue:

**Comment by AdamBrousseau** [comment]
Thanks, Fred. There's some stuff running at the moment but it may clear up in a few hours. I'll ping back if I see it free but if we can't do it till next week that's fine.

**Comment by AdamBrousseau** [comment]
@fredg02 at the moment there is only a couple of personal builds running so it might be a good time to do a restart. In general the builds should continue after a restart but I can't recall if this is the case with this Jenkins instance.

**Comment by fredg02** [comment]
Jenkins instance has been restarted. The plugin is installed now.

**Pull request merged**
