### PR TITLE
Update OMR Windows machines

### PR DESCRIPTION
**Pull request by vsebe**
Replace win2012-x86-2 with Windows 2019
and rename it win2019x64-openj9-1.
Add another machine to the pool: win2019x64-openj9-2

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
@AdamBrousseau fyi

**Comment by vsebe** [comment]
@jdekonin fyi

**Review by AdamBrousseau — APPROVED** [review]
This lftm. Although I'm not sure why we needed 2 different key types for the host key verification. This will need to be merged in conjunction with https://github.com/eclipse/omr/pull/6701.

**Comment by fredg02** [comment]
This change has been merged and deployed.

**Pull request merged**
