### PR TITLE
OMR: Add 2 new V2R4 z/OS systems from Marist

### PR DESCRIPTION
**Pull request by jdekonin**
Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
fyi @AdamBrousseau

**Comment by jdekonin** [comment]
@fredg02 This is ready. Thanks.

**Review by AdamBrousseau — APPROVED** [review]

**Comment by fredg02** [comment]
Commit has been merged and deployed. In the agent connection log I see the following errors (for both machines):
```
Permission denied, please try again.
Permission denied, please try again.
jenkins@148.100.36.158: Permission denied (publickey,password).
ERROR: Unable to launch the agent for ZISVJD09
java.io.EOFException: unexpected stream termination
```
https://ci.eclipse.org/omr/computer/ZISVJD09/log
https://ci.eclipse.org/omr/computer/ZISVJD10/log

**Comment by jdekonin** [comment]
Could be expected atm as the z/OS admins are cloning ZISVJD09 to ZISVJD10.  Waiting for the email on that to be complete.

**Pull request merged**
