### PR TITLE
Add 'warnings' plugin to JDT JIPP plugin configuration.

### PR DESCRIPTION
**Pull request by rgrunber**
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=565280
Signed-off-by: Roland Grunberg <rgrunber@redhat.com>

### CODE REVIEW

**Comment by fredg02** [comment]
Since the `warnings` plugin reached end-of-life (see https://plugins.jenkins.io/warnings/), I assume you want the `warnings-ng` plugin (see https://plugins.jenkins.io/warnings-ng/) instead.

**Comment by rgrunber** [comment]
> Since the `warnings` plugin reached end-of-life (see https://plugins.jenkins.io/warnings/), I assume you want the `warnings-ng` plugin (see https://plugins.jenkins.io/warnings-ng/) instead.

I saw that 'warnings-ng' is the newer one but when I checked eclipse-{platform,pde,equinox} , I saw the deprecated one so assumed there might be some reason that was used. Having checked the date, I guess it was froma while ago.

I'll make the change to warnings-ng.

**Comment by fredg02** [comment]
You are right, PDE and Equinox still use the legacy plugin. Platform is in the process of switching to the new plugin. For projects that do not rely on the legacy plugin, we recommend to start with the new one.

**Comment by fredg02** [comment]
The plugin is installed now.

**Pull request merged**
