### PR TITLE
Modify proxy machine that has VPN access to IBM Garage and UNB nodes

### PR DESCRIPTION
**Pull request by jdekonin**
* 13 UNB xLinux nodes
* 10 UNB pLinux nodes
* 2 IBM Garage AIX nodes
* 3 UNB MacOSX nodes

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
@AdamBrousseau I think this has it covered do you agree?

**Review by AdamBrousseau — APPROVED** [review]
lgtm. This can be merged/deployed.

**Comment by AdamBrousseau** [comment]
@fredg02 This is ready. Thanks.

**Comment by fredg02** [comment]
Change has been merged and deployed.

**Comment by jdekonin** [comment]
@fredg02 can you please accept the add to known hosts question on the connection to jenkins master to 140.211.168.16 `ssh -C -i /run/secrets/jenkins/ssh/id_rsa.omr jenkins@140.211.168.16`.

It seems we are having connection issues, like this one.
https://ci.eclipse.org/omr/computer/proxy/log

**Comment by fredg02** [comment]
Fixed.

**Pull request merged**
