### PR TITLE
Add gitlab bot to technology.subversive

### PR DESCRIPTION
**Pull request by heurtematte**
Jenkins updated also!

Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4060

### CODE REVIEW

**Comment by fredg02** [comment]
@heurtematte sorry for the delay. Please fix the conflicts, so this change can be merged.

**Comment by heurtematte** [comment]
> @heurtematte sorry for the delay. Please fix the conflicts, so this change can be merged.

done!

**Comment by fredg02** [comment]
@heurtematte Looks like there are a lot of unnecessary YAML formatting changes. Can you get rid of them?

**Comment by heurtematte** [comment]
I made a new generation but it's not really better. I wonder what changes the indentation. Since this is generated code, in my opinion it should not be part of a review.

**Comment by fredg02** [comment]
Interesting...

**Pull request merged**
