### PR TITLE
Update OSX instances as ip addresses changed with UNB power down

### PR DESCRIPTION
**Pull request by jdekonin**
Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
When will this change get deployed into production?

**Comment by fredg02** [comment]
Please let us know when it's a convenient time to restart the OpenJ9 JIPP.

**Comment by jdekonin** [comment]
If #68 can be merged as well and jenkins can be restarted with safe shutdown (I think its called). Meaning with the option to wait for running jobs to complete, not allowing new jobs to run.  Then now would be good.  Thanks.

**Comment by fredg02** [comment]
I've put the OpenJ9 JIPP into shutdown mode (no further builds can be scheduled).

**Pull request merged**
