### PR TITLE
Update OpenJ9 Github API Token Cred ID

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Related https://bugs.eclipse.org/bugs/show_bug.cgi?id=550740#c15

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Is this deployed? I don't see the changes taking effect.

**Comment by fredg02** [comment]
I had applied the change in the Web UI manually before, so I saw no immediate need to redeploy the instance, but it's done now.

**Comment by AdamBrousseau** [comment]
Ok then there's something else wrong as our jobs are still giving auth errors
https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-OpenJ9/1233/console
```
GitHub pull request #6993 of commit a59ba251067e34325c39015f142c84faa55d5747, no merge conflicts.
Unable to query GitHub for status of PullRequestorg.kohsuke.github.HttpException: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:703)
	at org.kohsuke.github.Requester._to(Requester.java:306)
	at org.kohsuke.github.Requester.to(Requester.java:247)
	at org.kohsuke.github.GHRepository.getPullRequest(GHRepository.java:715)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getActualPullRequest(GhprbRepository.java:337)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.getPullRequest(GhprbPullRequest.java:827)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onStarted(GhprbBuilds.java:112)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:20)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:238)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:285)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: 401, message: 'Unauthorized' for URL: https://api.github.com/repos/eclipse/openj9/pulls/6993
...
```

**Comment by fredg02** [comment]
IIUC, the credentials are taken from the Git SCM config, which was set to "none" in the job config. I've set it to the GitHub bot credentials now. Can you try again?

**Comment by AdamBrousseau** [comment]
It's not the scm step that's failing it's the GH PR Builder plugin failing to update the status on the PR.

**Comment by fredg02** [comment]
The GitHub Pull Request Builder plugin seems to be set up correctly, since it can post comments on PRs, see: https://github.com/eclipse/openj9/pull/7098.

**Comment by AdamBrousseau** [comment]
Working now. Fired a build from that PR.

**Comment by fredg02** [comment]
OK. Thanks for the feedback.

**Comment by AdamBrousseau** [comment]
Hmm, still not working for all builds
https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-CopyrightCheck-OpenJ9/18847/console

**Comment by AdamBrousseau** [comment]
Any thoughts on the CopyrightCheck and LineEndings Check builds? Also I cannot manually trigger these builds from the PRs. They run automatically but you can also run them with trigger.

**Comment by AdamBrousseau** [comment]
Seems to be working now

**Pull request merged**
