### PR TITLE
OMR: Add 2 new zLinux servers from Marist

### PR DESCRIPTION
**Pull request by jdekonin**
* related eclipse/omr#6711

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
fyi @AdamBrousseau as discussed, working in 2 replacement Linux 390 machines.

**Comment by jdekonin** [comment]
This is ready to merge/deploy, thank you.

**Review by AdamBrousseau — COMMENTED** [review]
The rsa keys look the same. They should match each node's value. Should be in /etc/ssh/ssh_host_rsa.pub if i recall correctly.

**Comment by jdekonin** [comment]
I needed to regenerate on both systems as they were built from the same image. :)

**Comment by fredg02** [comment]
@AdamBrousseau is this ready to be merged?

**Comment by AdamBrousseau** [comment]
@fredg02 I believe so.

**Comment by fredg02** [comment]
Change has been merged and deployed.

SSH private key is rejected on both machines:
```
ERROR: Server rejected the 1 private key(s) for jenkins (credentialId:omr-agents-ssh/method:publickey)
```

**Comment by jdekonin** [comment]
I'm guessing this is something to do with the userid not being `jenkins` but `omr`.  I can use the same key that jenkins uses to connect without issues to the old systems.  I double checked the accuracy for the `manuallyProvidedKeyVerificationStrategy` key value as well.

**Comment by fredg02** [comment]
Yes. Can you change the user to be `jenkins` instead of `omr`?

**Comment by jdekonin** [comment]
The machine is being shared with the OpenJ9 project which has already been using the jenkins id for some time.

Guessing the credentials aren't in course control I can modify like we did for user1 on the z/OS systems?

**Comment by fredg02** [comment]
I've created a separate Jenkins credential with username `omr`. Agents are connected now.

We should try hard to not let this become a (bad) habit.

**Comment by jdekonin** [comment]
Thanks @fredg02.  We were actually thinking of more machine sharing between OpenJ9 and OMR projects, so as this becomes more common for OMR systems to use the `omr-agents-ssh-rh7` credential, fewer will be using the `omr-agents-ssh` credential.  At some point in the hopefully not too distant future the `omr-agents-ssh` credential would be able to be removed.

**Pull request merged**
