### PR TITLE
Modify UNB connection details to resolve on the proxy

### PR DESCRIPTION
**Pull request by jdekonin**
Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
Once merged if this can be deployed to jenkins can be restarted with safe shutdown (I think its called). Meaning with the option to wait for running jobs to complete, not allowing new jobs to run.

fyi @pshipton

**Comment by pshipton** [comment]
@fredg02 OpenJ9 Jenkins is in state "Jenkins is going to shut down. No further builds will be performed". All the running jobs were stuck, either after running all the tests but before finalizing the test run, or before getting started with the testing. I've force-ably terminated all the jobs.  Now Jenkins is just sitting there, not restarting or running anything. Can you please help restart it so we can get back to normal.

**Comment by fredg02** [comment]
OpenJ9 JIPP has been redeployed with changes from #68 and #67 .

This was an attempt to do a "safe restart" without killing builds. Due to the structure of the builds (builds spawning other builds, etc.) this does not work on the OpenJ9 JIPP. We will need to find another way to do a restart which is less disruptive.

**Comment by pshipton** [comment]
I opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=553268

**Comment by pshipton** [comment]
@jdekonin I also note this "fix" didn't entirely work. I was supposed to fix the `cent-x64-*` machines, but these machines are still unreachable. The Mac machines did come online, as did AIX 5-9.
```
$ ssh -C -i /run/secrets/jenkins/ssh/id_rsa.openj9 jenkins@140.211.168.230 "ssh -i ~/.ssh/id_rsa.aix jenkins@cent6-x64-1 'wget -qO slave.jar https://ci.eclipse.org/openj9/jnlpJars/slave.jar ; exec java -jar slave.jar'"

Host key verification failed.
ERROR: Unable to launch the agent for cent6-x64-1
java.io.EOFException: unexpected stream termination
	at hudson.remoting.ChannelBuilder.negotiate(ChannelBuilder.java:415)
	at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:360)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:434)
	at hudson.slaves.CommandLauncher.launch(CommandLauncher.java:154)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:297)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by pshipton** [comment]
osx1014-x86-1 is still offline as well. The other Macs are online.
```
$ ssh -C -i /run/secrets/jenkins/ssh/id_rsa.openj9 jenkins@140.211.168.230 "ssh -i ~/.ssh/id_rsa.aix jenkins@ osx1014-x86-1 'wget -qO slave.jar https://ci.eclipse.org/openj9/jnlpJars/slave.jar ; exec java -jar slave.jar'"
kex_exchange_identification: Connection closed by remote host
ERROR: Unable to launch the agent for osx1014-x86-1
java.io.EOFException: unexpected stream termination
	at hudson.remoting.ChannelBuilder.negotiate(ChannelBuilder.java:415)
	at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:360)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:434)
	at hudson.slaves.CommandLauncher.launch(CommandLauncher.java:154)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:297)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by jdekonin** [comment]
osx1014-x86-1 was a typo.  I've corrected it via https://github.com/eclipse-cbi/jiro/pull/69 which has been merged.

cent6-x64-* needed to be auth'd from the vpn portal to the UNB machines which I've performed.  Everything but ub16x64j91 and the Power8 instance from UNB should now be online.

**Pull request merged**
